// Hidden State — news articles.
//
// TO ADD AN ARTICLE: copy one block, put it at the TOP of the list, and change
// the fields. Newest first. `slug` becomes the web address (/news/<slug>) so
// keep it lowercase with dashes and never reuse one.
//
// Photos live in /public/news/ — drop the image there and reference it as
// "/news/your-file.jpg". Use the PHOTO from your poster, not the whole poster:
// each article is typeset in code so it reads on a phone and can be found by
// search engines. Add `lineup: [...]` for events and it renders as a line-up block.

export const ARTICLES = [
  {
    slug: "creamfields-2026",
    issue: "VOL. 01, NO. 5",
    date: "19 AUGUST 2026",
    sortDate: "2026-08-19",
    category: "EVENTS",
    categories: ["NEWS", "ARTISTS", "EVENTS", "INDUSTRY"],
    headline: "Creamfields, UK \u2014 27\u201330 August 2026",
    summary:
      "Four of dance music's biggest names head to Daresbury: Calvin Harris, Martin Garrix, Armin van Buuren and Ti\u00ebsto.",
    photo: null,
    poster: "/news/posters/creamfields-calvin-harris.jpg",
    posters: [
      "/news/posters/creamfields-calvin-harris.jpg",
      "/news/posters/creamfields-martin-garrix.jpg",
      "/news/posters/creamfields-armin-van-buuren.jpg",
      "/news/posters/creamfields-tiesto.jpg",
    ],
    body: [
      "Creamfields returns to Daresbury from 27 to 30 August 2026, and the bill at the top reads like a history of the last two decades of dance music.",
      "Calvin Harris has shaped modern dance music with global hits, iconic collaborations and festival performances that define the format. Martin Garrix rose to global fame on his signature festival sound and has stayed at the front of the scene ever since.",
      "Armin van Buuren has spent decades defining the global trance scene through his productions, his radio show and his live performances. Ti\u00ebsto's career spans more than twenty years, from pioneering trance to dominating modern festival stages, reinventing himself repeatedly along the way.",
    ],
    kicker: "27\u201330 August 2026 \u2014 Daresbury",
    signoff: null,
    tags: ["CALVIN HARRIS", "MARTIN GARRIX", "ARMIN VAN BUUREN", "TI\u00cbSTO"],
    footnote: null,
    link: null,
    linkLabel: null,
  },
  {
    slug: "black-coffee-hi-ibiza",
    issue: "VOL. 01, NO. 5",
    date: "19 AUGUST 2026",
    sortDate: "2026-08-19",
    category: "EVENTS",
    categories: ["NEWS", "ARTISTS", "EVENTS"],
    headline: "Black Coffee at Hi Ibiza",
    summary:
      "The South African Afro House figurehead runs his Ibiza dates through August and September, closing on 3 October.",
    photo: null,
    poster: "/news/posters/black-coffee.jpg",
    body: [
      "Black Coffee plays Hi Ibiza across August and September, with a closing set on 3 October.",
      "The South African DJ and producer is known for a signature blend of Afro House, deep electronic sound and African influences, built into a career that spans the biggest festivals and clubs worldwide. With a Grammy Award and a reputation as one of Africa's most influential electronic artists, he continues to shape the global sound of Afro House.",
    ],
    kicker: "August 22, 29 \u00b7 September 5, 12, 19, 26 \u00b7 Closing set October 3",
    signoff: null,
    tags: ["AFRO HOUSE", "HI IBIZA", "SOUTH AFRICA"],
    footnote: null,
    link: null,
    linkLabel: null,
  },
  {
    slug: "indira-paganotto-hi-ibiza",
    issue: "VOL. 01, NO. 5",
    date: "19 AUGUST 2026",
    sortDate: "2026-08-19",
    category: "EVENTS",
    categories: ["NEWS", "ARTISTS", "EVENTS"],
    headline: "Indira Paganotto at Hi Ibiza",
    summary:
      "The Spanish psy-techno force takes Hi Ibiza through August and September, closing on 4 October.",
    photo: null,
    poster: "/news/posters/indira-paganotto.jpg",
    body: [
      "Indira Paganotto plays Hi Ibiza across August and September, closing on 4 October.",
      "The Spanish DJ and producer is one of the leading names in psy-techno, known for an energetic, hypnotic sound that blends underground techno with psytrance influences. She has performed at major festivals and clubs worldwide, including Tomorrowland, Awakenings, EXIT and EDC Las Vegas, and founded ARTCORE, a label closely associated with the modern psy-techno movement.",
    ],
    kicker: "August 23, 30 \u00b7 September 6, 13, 20, 27 \u00b7 Closing set October 4",
    signoff: null,
    tags: ["PSY-TECHNO", "HI IBIZA", "ARTCORE"],
    footnote: null,
    link: null,
    linkLabel: null,
  },
  {
    slug: "miss-monique-hi-ibiza",
    issue: "VOL. 01, NO. 5",
    date: "19 AUGUST 2026",
    sortDate: "2026-08-19",
    category: "EVENTS",
    categories: ["NEWS", "ARTISTS", "EVENTS"],
    headline: "Miss Monique at Hi Ibiza",
    summary:
      "The Ukrainian progressive house and melodic techno name plays through August and September, closing on 24 September.",
    photo: null,
    poster: "/news/posters/miss-monique.jpg",
    body: [
      "Miss Monique plays Hi Ibiza across August and September, with a closing set on 24 September.",
      "The Ukrainian DJ and producer is one of the leading names in progressive house and melodic techno. Known for a powerful, emotional sound and for performing worldwide, she has become a major force in the modern electronic music scene, playing some of the world's biggest festivals and clubs.",
    ],
    kicker: "August 20, 27 \u00b7 September 3, 10, 17 \u00b7 Closing set September 24",
    signoff: null,
    tags: ["PROGRESSIVE HOUSE", "MELODIC TECHNO", "HI IBIZA"],
    footnote: null,
    link: null,
    linkLabel: null,
  },
  {
    slug: "b-mike-joins-hidden-state",
    issue: "VOL. 01, NO. 4",
    date: "19 AUGUST 2026",
    sortDate: "2026-08-19",
    category: "ARTISTS",
    categories: ["NEWS", "ARTISTS"],
    headline: "B.MIKE joins Hidden State, creating something new and unique",
    summary:
      "A young Romanian DJ with perfect pitch, a festival record already behind him, and a charitable project raising funds for autism therapy.",
    photo: "/artists/b-mike.jpg",
    poster: "/news/posters/b-mike.jpg",
    caption: "B.MIKE \u2014 Heartbeat Vibes",
    body: [
      "B.MIKE started DJing in 2022 and is part of OWPN Academy. Since then he has performed at major festivals including UNTOLD, Electric Castle, Flight Festival, Take Off Festival, Codru Festival, Snow Fest France, Nassau Festival, Univibes and Takeover.",
      "His achievements include the Timisoara Music Awards New Talent Award (2023) and Tech-House Award (2024), a place among the five finalists in the Drum & Bass category (2025), and an Excellence Award from Flight Festival in 2025.",
      "He has played venues across Romania including Fratelli Timisoara, Form Space Cluj and Underground Pub Iasi, sharing stages with Carla's Dreams, DJ Project, Alina Eremia, Feli, Elena Gheorghe and Lidia Buble.",
      "Since March 2026 he has been part of EPICA, a charitable music project alongside Pascal Junior, Jayko, Silviu Andrei and Mindblow, raising funds to support access to therapy for people with autism. Musically he moves between 2000s retro, EDM, house, tech-house and drum & bass, with sets running from 128 to 175 BPM.",
    ],
    kicker: "B.MIKE \u2014 Heartbeat Vibes",
    signoff: "Turning passion into ability, and ability into music.",
    tags: ["EDM / HOUSE", "TECH-HOUSE", "DRUM & BASS", "128\u2013175 BPM"],
    footnote: null,
    link: null,
    linkLabel: null,
  },
  {
    slug: "dj-tengu-joins-hidden-state",
    issue: "VOL. 01, NO. 3",
    date: "16 AUGUST 2026",
    sortDate: "2026-08-16",
    category: "ARTISTS",
    categories: ["NEWS", "ARTISTS"],
    headline: "DJ Tengu joins Hidden State, shaping the world of music",
    summary:
      "An old-school spirit joins the roster — hip-hop, R&B, funk, soul and classic urban records, played for atmosphere rather than effect.",
    photo: "/news/dj-tengu.jpg",
    poster: "/news/posters/dj-tengu.jpg",
    caption: "DJ Tengu behind the decks",
    body: [
      "DJ Tengu is driven by passion, talent, and a genuine love for music. With experience behind the decks and an unmistakable old-school spirit, he brings a sound that connects generations and keeps the energy alive.",
      "His selections travel through the golden sounds of old school hip-hop, R&B, funk, soul, rap and classic urban music, blending timeless records with his own style and personality.",
      "For DJ Tengu, music is more than just playing tracks — it's about creating an atmosphere, telling a story and making people feel every beat. With dedication, character and a constant desire to evolve, he continues to shape his own path through sound.",
    ],
    kicker: "Old soul. Real music. New energy.",
    signoff: "DJ Tengu — Creating the art.",
    tags: ["OLD SCHOOL HIP-HOP", "R&B / FUNK / SOUL", "CLASSIC URBAN"],
    footnote: "Some sounds are heard. Others are remembered.",
    link: null,
    linkLabel: null,
  },
  {
    slug: "astryon-festival-launch-party",
    issue: "VOL. 01, NO. 2",
    date: "15 AUGUST 2026",
    sortDate: "2026-08-15",
    category: "EVENTS",
    categories: ["NEWS", "ARTISTS", "EVENTS"],
    headline: "Astryon Festival Launch Party",
    summary:
      "The first chapter opens on 28 August 2026 with a thirteen-artist line-up ahead of the festival itself.",
    photo: "/news/astryon-launch.jpg",
    poster: "/news/posters/astryon-launch.jpg",
    caption: "Astryon Festival Launch Party — 28 August 2026",
    body: [
      "The Astryon Festival Launch Party lands on 28 August 2026 — the opening moment before the festival's first chapter.",
      "Thirteen artists play across the night, spanning the range the festival itself will cover.",
    ],
    lineup: [
      "Maria", "RKO", "ANDREEA X", "Deysa", "Just Eddie", "Antoche Leon", "K SET",
      "RON HEWITT", "Damian", "Mike", "IXY", "Baranovschi", "No Form",
    ],
    eventDate: "28 AUGUST 2026",
    kicker: "28 August 2026",
    signoff: null,
    tags: ["LAUNCH PARTY", "13 ARTISTS", "ASTRYON FESTIVAL"],
    partners: [
      "Sonique Radio", "Electric Side Vision", "AHT Auto Haus Tudor",
      "MAVNO", "EDM Global News", "Arcentia Global Marketing",
    ],
    footnote: null,
    link: null,
    linkLabel: null,
  },
  {
    slug: "dj-mario-fill-and-dance",
    issue: "VOL. 01, NO. 1",
    date: "13 AUGUST 2025",
    sortDate: "2025-08-13",
    category: "MUSIC",
    categories: ["NEWS", "ARTISTS", "MUSIC"],
    headline: "Mario Daniel aka DJ Mario — new set",
    summary:
      "Fill & Dance explores the deeper, more energetic side of Afro House across a set built to be felt from beginning to end.",
    photo: "/news/dj-mario.jpg",
    poster: "/news/posters/dj-mario.jpg",
    caption: "DJ Mario — Fill & Dance",
    body: [
      "A new soundscape arrives through the latest set from DJ Mario, bringing together the energy, warmth and hypnotic character of Afro House in a journey designed to be felt from beginning to end.",
      "With a carefully selected tracklist, flowing transitions and a strong focus on rhythm, \u201CFill & Dance\u201D explores the deeper and more energetic side of Afro House. The set moves naturally between atmospheric moments, powerful grooves and uplifting rhythms, creating an experience that feels equally at home on the dancefloor, during a late-night drive, or simply with the volume turned up.",
      "More than just a collection of tracks, this set captures Mario's approach to music — letting the rhythm build naturally while keeping the energy alive throughout the entire journey.",
      "From the first beat to the final transition, Fill & Dance is about movement, atmosphere and connection through sound.",
    ],
    kicker: "DJ Mario — Fill & Dance",
    signoff: "Press play. Feel the rhythm. Fill the space.",
    tags: ["AFRO HOUSE / HOUSE", "DEEP GROOVES", "RHYTHM & ENERGY"],
    footnote: "Available now on YouTube.",
    link: "https://www.youtube.com/watch?v=oxJ0M7Qin5s",
    linkLabel: "LISTEN TO THE SET",
  },
];

export const getArticle = (slug) => ARTICLES.find((a) => a.slug === slug) || null;
