// Hidden State — placeholder content.
// Everything in this file is sample data so the site has something to show.
// Swap in the real roster, releases, events and articles when ready —
// every page reads from here, so this is the only file you need to edit.

export const ARTISTS = [
  {
    id: 1,
    name: "Stephanno Jr.",
    type: "DJ",
    genres: ["Afro House", "Afro Tech", "Deep House"],
    country: "Romania",
    location: "Romania",
    desc: "DJ, producer and founder of Hidden State.",
    bio:
      "As a DJ, producer and founder of Hidden State and all its divisions, Stephanno Jr. continues to build his own universe within the electronic music scene — connecting music, events, artists and creative experiences under one vision. Bringing his signature sound across Afro House, Afro Tech and Deep House, he plays with a sound shaped by years behind the decks and a constant drive to create something of his own.",
    photo: "/portrait.jpg",
    poster: "/news/posters/stephanno-astryon.jpg",
    instagram: "stephannojr",
    soundcloud: null,
    releases: [],
    upcoming: [{ name: "Astryon Festival", date: "18–20 JUN 2027", venue: "Romania — Main Stage" }],
    past: [],
  },
  {
    id: 2,
    name: "DJ Tengu",
    type: "DJ",
    genres: ["Old School Hip-Hop", "R&B", "Funk", "Soul", "Classic Urban"],
    country: null,
    location: null,
    desc: "Old soul, real music, new energy.",
    bio:
      "DJ Tengu is driven by passion, talent, and a genuine love for music. With experience behind the decks and an unmistakable old-school spirit, he brings a sound that connects generations and keeps the energy alive. His selections travel through the golden sounds of old school hip-hop, R&B, funk, soul, rap and classic urban music, blending timeless records with his own style and personality. For DJ Tengu, music is more than just playing tracks — it's about creating an atmosphere, telling a story and making people feel every beat.",
    photo: "/news/dj-tengu.jpg",
    poster: "/news/posters/dj-tengu.jpg",
    instagram: "djtengu",
    soundcloud: null,
    releases: [],
    upcoming: [],
    past: [],
  },
  {
    id: 3,
    name: "Mario Daniel",
    alias: "DJ Mario",
    type: "DJ",
    genres: ["Afro House", "House"],
    country: null,
    location: null,
    desc: "Deep grooves, rhythm and energy.",
    bio:
      "DJ Mario brings together the energy, warmth and hypnotic character of Afro House in sets designed to be felt from beginning to end. With a carefully selected tracklist, flowing transitions and a strong focus on rhythm, his Fill & Dance set explores the deeper and more energetic side of Afro House — moving naturally between atmospheric moments, powerful grooves and uplifting rhythms. More than a collection of tracks, it captures his approach to music: letting the rhythm build naturally while keeping the energy alive throughout the entire journey.",
    photo: "/artists/dj-mario.jpg",
    poster: "/news/posters/dj-mario.jpg",
    instagram: "djmario",
    soundcloud: null,
    releases: [],
    upcoming: [],
    past: [],
  },
  {
    id: 4,
    name: "B.MIKE",
    alias: "Heartbeat Vibes",
    type: "DJ",
    genres: ["2000s Retro", "EDM", "House", "Tech-House", "Drum & Bass"],
    country: "Romania",
    location: "Romania",
    desc: "Turning passion into ability, and ability into music.",
    bio:
      "B.MIKE started DJing in 2022 and is part of OWPN Academy. Since then he has played major festivals including UNTOLD, Electric Castle, Flight Festival, Take Off Festival, Codru Festival, Snow Fest France, Nassau Festival, Univibes and Takeover, alongside venues across Romania such as Fratelli Timisoara, Form Space Cluj and Underground Pub Iasi \u2014 sharing stages with Carla's Dreams, DJ Project, Alina Eremia, Feli, Elena Gheorghe and Lidia Buble. His awards include the Timisoara Music Awards New Talent Award (2023) and Tech-House Award (2024), a place among the five Drum & Bass finalists (2025), and an Excellence Award from Flight Festival in 2025. Since March 2026 he has been part of EPICA, a charitable music project alongside Pascal Junior, Jayko, Silviu Andrei and Mindblow. His sets move between 2000s retro, EDM, house, tech-house and drum & bass, running anywhere from 128 to 175 BPM.",
    photo: "/artists/b-mike.jpg",
    poster: "/news/posters/b-mike.jpg",
    instagram: null,
    releases: [],
    upcoming: [],
    past: [],
  },
  {
    id: 5,
    name: "DJ Stephanno",
    alias: "Model 1",
    type: "DJ",
    genres: ["House", "Techno", "Vinyl"],
    country: "Romania",
    location: "Romania",
    desc: "Two decades of experience. One passion. Pure vinyl.",
    bio:
      "With over 20 years behind the decks, DJ Stephanno / Model 1 is a true lover of the art of DJing. A vinyl-driven artist with a deep connection to the roots of electronic music, he brings together the timeless character of house and techno with experience, instinct and an authentic underground spirit. His sets are built around groove, atmosphere and storytelling, allowing the music to speak naturally and the dancefloor to become part of the journey.",
    photo: "/artists/dj-stephanno-model1.jpg",
    poster: "/news/posters/dj-stephanno-model1.jpg",
    instagram: "djstephanno",
    instagramExtra: "circoloco",
    releases: [],
    upcoming: [],
    past: [],
  },
];

// Shown under the roster on the Artists and Agency pages.
export const ROSTER_NOTE = "More DJs and producers will join.";

export const FILTERS = ["ALL", "DJS", "PRODUCERS", "LIVE ACTS"];

export const FILTER_MAP = { DJS: "DJ", PRODUCERS: "Producer", "LIVE ACTS": "Live Act" };

export const RELEASES = [
  { id: 1, artist: "Nomi Reyes", title: "Low Light EP", genre: "Deep House", date: "AUG 08", catalog: "HS-013", artwork: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80", status: "latest" },
  { id: 2, artist: "Kael Vance", title: "Terra Nova", genre: "Melodic House", date: "JUL 28", catalog: "HS-012", artwork: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80", status: "latest" },
  { id: 3, artist: "Ilé", title: "Root Work", genre: "Afro Tech", date: "JUL 14", catalog: "HS-011", artwork: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800&q=80", status: "latest" },
  { id: 4, artist: "Dax Marlow", title: "Static Bloom", genre: "Tech House", date: "SEP 05", catalog: "HS-015", artwork: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80", status: "upcoming" },
  { id: 5, artist: "Sable & Rho", title: "Two Rooms", genre: "Organic House", date: "SEP 19", catalog: "HS-016", artwork: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800&q=80", status: "upcoming" },
  { id: 6, artist: "Stephanno JR.", title: "Hidden State 010", genre: "House", date: "MAY 02", catalog: "HS-010", artwork: "https://images.unsplash.com/photo-1478147427282-58a87a120781?w=800&q=80", status: "discography" },
  { id: 7, artist: "Nomi Reyes", title: "Hidden State 007", genre: "Deep House", date: "FEB 21", catalog: "HS-007", artwork: "https://images.unsplash.com/photo-1571266028243-d220c9c3b31d?w=800&q=80", status: "discography" },
];

export const FEATURED_RELEASE = {
  artist: "Stephanno JR.",
  title: "Hidden State 014",
  genre: "Afro House / Afro Tech",
  date: "AUG 15, 2026",
  catalog: "HS-014",
  description:
    "A five-track EP built around restraint — polyrhythmic percussion, long-form builds, and almost no drop. The label's most understated release to date.",
  artwork: "https://images.unsplash.com/photo-1614149162883-504ce4d13909?w=1200&q=80",
};

export const EVENTS = [
  {
    id: 1,
    slug: "astryon-festival-2027",
    status: "upcoming",
    name: "Astryon Festival",
    subtitle: "The First Chapter",
    date: "18\u201320 JUNE 2027",
    sortDate: "2027-06-18",
    venue: "Main Stage",
    city: "Black Sea Coast",
    country: "Romania",
    artwork: null, // festival artwork not supplied yet — a typographic panel shows instead
    description:
      "Three days of electronic music on Romania's Black Sea coast, with more than 200 DJs and producers playing across multiple stages \u2014 techno, house, Afro House and further out into ambient and experimental. Stephanno Jr. takes the main stage.",
    facts: ["72 HOURS OF MUSIC", "OVER 200 ARTISTS", "MULTIPLE STAGES"],
    lineup: ["Stephanno Jr."],
    tickets: "https://www.astryonfestival.com/tickets",
    website: "https://www.astryonfestival.com",
    instagram: "astryon",
    gallery: [],
  },
  {
    id: 2,
    slug: "creamfields-2026",
    status: "upcoming",
    name: "Creamfields",
    subtitle: "Daresbury, UK",
    date: "27\u201330 AUGUST 2026",
    sortDate: "2026-08-27",
    venue: null,
    city: "Daresbury",
    country: "United Kingdom",
    artwork: "/news/posters/creamfields-calvin-harris.jpg",
    description:
      "Four nights at Daresbury with Calvin Harris, Martin Garrix, Armin van Buuren and Ti\u00ebsto among the headliners.",
    facts: ["4 NIGHTS", "DARESBURY, UK"],
    lineup: ["Calvin Harris", "Martin Garrix", "Armin van Buuren", "Ti\u00ebsto"],
    lineupLabel: "\u2014 HEADLINERS \u2014",
    tickets: null,
    website: null,
    article: "creamfields-2026",
    gallery: [],
  },
  {
    id: 3,
    slug: "black-coffee-hi-ibiza",
    status: "upcoming",
    name: "Black Coffee",
    subtitle: "Hi Ibiza",
    date: "22 AUG \u2013 3 OCT 2026",
    sortDate: "2026-08-22",
    venue: "Hi Ibiza",
    city: "Ibiza",
    country: "Spain",
    artwork: "/news/posters/black-coffee.jpg",
    description:
      "Black Coffee's Ibiza dates run through August and September, closing on 3 October.",
    facts: ["AUG 22, 29", "SEP 5, 12, 19, 26", "CLOSING SET OCT 3"],
    lineup: ["Black Coffee"],
    tickets: null,
    website: null,
    article: "black-coffee-hi-ibiza",
    gallery: [],
  },
  {
    id: 4,
    slug: "indira-paganotto-hi-ibiza",
    status: "upcoming",
    name: "Indira Paganotto",
    subtitle: "Hi Ibiza",
    date: "23 AUG \u2013 4 OCT 2026",
    sortDate: "2026-08-23",
    venue: "Hi Ibiza",
    city: "Ibiza",
    country: "Spain",
    artwork: "/news/posters/indira-paganotto.jpg",
    description:
      "Indira Paganotto's psy-techno residency runs through August and September, closing on 4 October.",
    facts: ["AUG 23, 30", "SEP 6, 13, 20, 27", "CLOSING SET OCT 4"],
    lineup: ["Indira Paganotto"],
    tickets: null,
    website: null,
    article: "indira-paganotto-hi-ibiza",
    gallery: [],
  },
  {
    id: 5,
    slug: "miss-monique-hi-ibiza",
    status: "upcoming",
    name: "Miss Monique",
    subtitle: "Hi Ibiza",
    date: "20 AUG \u2013 24 SEP 2026",
    sortDate: "2026-08-20",
    venue: "Hi Ibiza",
    city: "Ibiza",
    country: "Spain",
    artwork: "/news/posters/miss-monique.jpg",
    description:
      "Miss Monique plays Hi Ibiza across August and September, with a closing set on 24 September.",
    facts: ["AUG 20, 27", "SEP 3, 10, 17", "CLOSING SET SEP 24"],
    lineup: ["Miss Monique"],
    tickets: null,
    website: null,
    article: "miss-monique-hi-ibiza",
    gallery: [],
  },
  {
    id: 6,
    slug: "euphoria",
    status: "past",
    name: "Euphoria",
    subtitle: "An Obscure Experience",
    date: "6 MARCH 2026",
    sortDate: "2026-03-06",
    venue: null,
    city: null,
    country: null,
    artwork: "/events/euphoria-poster.jpg",
    description:
      "Euphoria brought Stephanno Jr. and Mario Daniel together behind the decks for the night, with CEASE playing alongside them and a special guest on the bill. All genres, one room, doors at 19:00.",
    facts: ["ALL GENRES", "DOORS 19:00", "SPECIAL GUEST"],
    lineup: ["Stephanno Jr.", "Mario Daniel", "CEASE"],
    lineupLabel: "\u2014 ARTISTS PERFORMING \u2014",
    tagline: "Be euphoric, be there.",
    tickets: null,
    website: null,
    article: null,
    photosLink:
      "https://www.dropbox.com/scl/fi/i977jp8rgasjqdig12j90/EUPHORIA.zip?rlkey=vy198l3nlhnd77iwkr0gr70rg&dl=1",
    photosLinkLabel: "EUPHORIA PHOTOS",
    gallery: [
              "/events/euphoria/01.jpg",
              "/events/euphoria/02.jpg",
              "/events/euphoria/03.jpg",
              "/events/euphoria/04.jpg",
              "/events/euphoria/05.jpg",
              "/events/euphoria/06.jpg",
              "/events/euphoria/07.jpg",
              "/events/euphoria/08.jpg",
              "/events/euphoria/09.jpg",
              "/events/euphoria/10.jpg",
              "/events/euphoria/11.jpg",
              "/events/euphoria/12.jpg",
              "/events/euphoria/13.jpg",
              "/events/euphoria/14.jpg"
    ],
  },
];

// Shown under the events list.
export const EVENTS_NOTE = "More events to come.";

export const HERO = {
  category: "EXCLUSIVE",
  headline: "Inside the Session That Redefined Afro Tech",
  excerpt:
    "A year after their breakout Boiler Room set, Stephanno JR. opens the studio door on the record that pulled a continent's sound into the main room.",
  date: "AUG 14, 2026",
  readTime: "9 MIN READ",
  image:
    "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1600&q=80",
};

export const ARTICLES = [
  {
    id: 1,
    category: "ARTISTS",
    headline: "The Producers Quietly Building Organic House's Second Wave",
    excerpt: "Five names A&Rs are watching before the festival circuit catches up.",
    date: "AUG 12",
    readTime: "6 MIN",
    image: "https://images.unsplash.com/photo-1571266028243-d220c9c3b31d?w=1200&q=80",
    span: "lg",
  },
  {
    id: 2,
    category: "RELEASES",
    headline: "HIDDEN STATE 014: A Catalog Built on Restraint",
    excerpt: "Track-by-track notes from the label's most understated EP yet.",
    date: "AUG 11",
    readTime: "4 MIN",
    image: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=900&q=80",
    span: "md",
  },
  {
    id: 3,
    category: "INTERVIEWS",
    headline: "\u201cI Don't Design for the Drop\u201d — A Conversation on Tension",
    excerpt: "One of dance music's most private producers finally talks process.",
    date: "AUG 09",
    readTime: "11 MIN",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=900&q=80",
    span: "md",
  },
  {
    id: 4,
    category: "INDUSTRY",
    headline: "What Door Policy Actually Protects, According to Four Promoters",
    excerpt: "Inside the unglamorous mechanics keeping underground rooms underground.",
    date: "AUG 08",
    readTime: "7 MIN",
    image: "https://images.unsplash.com/photo-1478147427282-58a87a120781?w=1000&q=80",
    span: "wide",
  },
  {
    id: 5,
    category: "EVENTS",
    headline: "Notes From Three Nights at the Warehouse Nobody Announced",
    excerpt: "A dispatch from the room dance music forgot to put on a flyer.",
    date: "AUG 06",
    readTime: "5 MIN",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=900&q=80",
    span: "md",
  },
  {
    id: 6,
    category: "MUSIC",
    headline: "The Slow Return of the 90-Minute Set",
    excerpt: "Why more DJs are asking promoters for the room back.",
    date: "AUG 05",
    readTime: "8 MIN",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=900&q=80",
    span: "md",
  },
];
