/*
  SELF-HOST THE TYPEFACES.

  Run once, on a machine with normal internet:  npm run fonts

  WHAT IT DOES. Asks Google for the stylesheet the site already uses, pulls
  down every .woff2 it names, writes them into public/fonts/, writes a local
  stylesheet pointing at them, and rewires index.html to use it. After that
  the site never asks Google for anything.

  WHY BOTHER, when the link in the head already works. Three reasons, in order
  of how much they matter:
    • Offline. The installed app currently falls back to Georgia with no
      signal. Self-hosted, it does not.
    • One less company watching. A font request tells Google the address of
      every page every visitor opens.
    • One less thing that can be slow. Google being slow is your site being
      slow, and you cannot do anything about it.

  It is written to be safe to run twice: existing files are overwritten, and
  index.html is only rewritten if it still points at Google.

  THE USER-AGENT MATTERS. Google serves a different stylesheet to each
  browser — old ones get .ttf, modern ones get .woff2, which is roughly half
  the size. Asking as a current Chrome is what gets the good files.
*/
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2" +
  "?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400;0,6..96,700;0,6..96,900;1,6..96,400;1,6..96,700" +
  "&family=EB+Garamond:ital,wght@0,400;0,500;1,400" +
  "&family=Space+Mono:ital,wght@0,400;0,700;1,400" +
  "&display=swap";

const ROOT = new URL("../", import.meta.url).pathname;
const OUT = join(ROOT, "public/fonts");

const get = async (url, as = "text") => {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} on ${url}`);
  return as === "text" ? res.text() : Buffer.from(await res.arrayBuffer());
};

async function main() {
  await mkdir(OUT, { recursive: true });

  let css = await get(CSS_URL);
  const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]))];
  if (!urls.length) throw new Error("no font files named in the stylesheet");

  console.log(`${urls.length} font files to fetch`);
  let bytes = 0;

  for (const url of urls) {
    // gstatic paths are already unique and descriptive; the last two segments
    // keep that meaning without the directory tree.
    const name = url.split("/").slice(-2).join("-").replace(/[^\w.-]/g, "_");
    const buf = await get(url, "buffer");
    await writeFile(join(OUT, name), buf);
    css = css.split(url).join(`/fonts/${name}`);
    bytes += buf.length;
    process.stdout.write(".");
  }

  await writeFile(join(OUT, "fonts.css"),
    "/* Generated by scripts/fonts.mjs — do not edit by hand. */\n" + css);
  console.log(`\npublic/fonts/ — ${urls.length} files, ${(bytes / 1024).toFixed(0)} KB`);

  const idx = join(ROOT, "index.html");
  let html = await readFile(idx, "utf8");
  if (html.includes("fonts.googleapis.com/css2")) {
    html = html
      .replace(/\n?\s*<link rel="preconnect" href="https:\/\/fonts\.(googleapis|gstatic)\.com"[^>]*>/g, "")
      .replace(/<link id="hs-fonts" rel="stylesheet" href="https:\/\/fonts\.googleapis\.com[^"]*"\s*\/>/,
               '<link rel="preload" as="style" href="/fonts/fonts.css" />\n'
             + '    <link id="hs-fonts" rel="stylesheet" href="/fonts/fonts.css" />');
    await writeFile(idx, html);
    console.log("index.html now points at the local copies");
  } else {
    console.log("index.html already local — left alone");
  }

  console.log("\nOne more thing: the service worker's font rule in public/sw.js\n" +
              "is now dead code. Harmless, but you can delete it.");
}

main().catch((e) => { console.error("\nfailed:", e.message); process.exit(1); });
