/*
  BUILD THE SITEMAP FROM THE CONTENT.

  It used to be typed by hand. It had thirty-three entries, was months out of
  date, listed pages that no longer exist and was missing every page added
  since — including the pool. A hand-written sitemap is wrong the moment
  anybody adds an article and does not remember to come back here.

  This reads the same JSON the site itself reads, so it cannot disagree with
  the site. It runs before every build.

  WHAT IS DELIBERATELY LEFT OUT. Passes, the scanner, the door list, the
  console and the login: private pages, and a sitemap is an invitation.

  Run:  npm run sitemap    (or just npm run build, which runs it first)
*/
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("../", import.meta.url).pathname;
const BASE = "https://hiddenstategroup.com";

const read = async (f) => JSON.parse(await readFile(join(ROOT, "src/content", f), "utf8"));
const today = new Date().toISOString().slice(0, 10);

/*
  Priority is a hint about relative importance WITHIN this site, not a claim
  about the internet. The home page leads, the sections that change follow,
  and the pages that exist to be linked to rather than found sit lowest.
*/
const SECTIONS = [
  ["/", 1.0], ["/news", 0.9], ["/artists", 0.9], ["/events", 0.9],
  ["/agency", 0.8], ["/records", 0.8], ["/mixes", 0.7],
  ["/about", 0.6], ["/contact", 0.6], ["/pool", 0.5],
];

async function main() {
  const [artists, events, news, mixes, records] = await Promise.all(
    ["artists.json", "events.json", "news.json", "mixes.json", "records.json"].map(read)
  );

  const urls = [...SECTIONS.map(([loc, p]) => ({ loc, p, mod: today }))];

  const add = (list, path, priority, key = "id", dated = null) => {
    for (const item of list) {
      const slug = item[key];
      if (!slug) continue;
      urls.push({
        loc: `${path}/${slug}`,
        p: priority,
        // A real date where the content carries one. Claiming everything
        // changed today is the fastest way to be ignored.
        mod: (dated && item[dated] && String(item[dated]).slice(0, 10)) || today,
      });
    }
  };

  add(artists, "/artists", 0.7, "id");
  add(events, "/events", 0.7, "id", "date");
  add(news, "/news", 0.7, "slug", "date");
  add(mixes, "/mixes", 0.6, "slug");
  // Releases live on the records page rather than at their own address, so
  // they are counted but not listed. Listing a URL that redirects is worse
  // than not listing it.
  void records;

  const seen = new Set();
  const body = urls
    .filter((u) => (seen.has(u.loc) ? false : seen.add(u.loc)))
    .map((u) =>
      `  <url><loc>${BASE}${u.loc}</loc>` +
      `<lastmod>${/^\d{4}-\d{2}-\d{2}$/.test(u.mod) ? u.mod : today}</lastmod>` +
      `<priority>${u.p.toFixed(1)}</priority></url>`
    )
    .join("\n");

  await writeFile(
    join(ROOT, "public/sitemap.xml"),
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/sitemap.mjs — do not edit by hand. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`
  );
  console.log(`sitemap.xml — ${seen.size} pages`);
}

main().catch((e) => { console.error("sitemap failed:", e.message); process.exit(1); });
